<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>
  <input-symbol key="component" required="yes" />
  <input-symbol key="prompt" required="yes" />
  
  <let key="button">
    document.getElementById('${component.clientId}')
  </let>  
  
  <body>
    <unique>
      function attachOnClick(button, prompt) {
        if (!button) return;
        button.addEventListener('click', function(event) {
          if (!confirm(prompt)) {
            event.preventDefault();
          }
        });
      }    
    </unique>
  </body>
  <initialization>
    attachOnClick(${button}, '${prompt}');
  </initialization>
</script>