<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>
  <input-symbol key="compClientId" required="yes" />
  
  <initialization>
    var tableId = '${compClientId}'.slice(0, -2);
    var tableElement = document.getElementById(tableId);

    if (tableElement) {
        addFirstLast(tableElement);
    }
  </initialization>
</script>