#!/bin/bash

SIPX_USER=sipx

DEFAULT_PLATFORM=centos-7

DEFAULT_ARCHITECTURE=x86_64

DEFAULT_SUBPROJECT=sipx

DEFAULT_VERSION=25.01

SIPXCOM_USER_GROUP=sipxcom-dev@googlegroups.com

THIS_MASTER_BUILD_SCRIPT=$(readlink -f ${BASH_SOURCE[0]})

SOURCE_DIR=$(dirname ${THIS_MASTER_BUILD_SCRIPT})

BUILD_DIR=${SOURCE_DIR}/build

LOCAL_REPO=

DEFAULT_INSTALL_OPTIONS="-y --setopt=metadata_expire=never"
#DEFAULT_INSTALL_OPTIONS="-y --cacheonly"


function checkUser()
{
    echo "Begin checkUser(): SUDO_USER=${SUDO_USER}, USER=${USER}, SIPX_USER=${SIPX_USER}"

    if [ "${SUDO_USER}" != "${SIPX_USER}" ] || [ "${USER}" != "root" ]; then
        echo "
        Error: You must run this script with sudo root privileges as user ${SIPX_USER}. 
        
        Please setup your instance as follows:

        yum update -y
        
        useradd -m ${SIPX_USER}

        passwd ${SIPX_USER}

        visudo (append):
            # add ${SIPX_USER} as sudo user
            ${SIPX_USER}    ALL=(ALL)       NOPASSWD:ALL

        yum install -y sudo

        su ${SIPX_USER}

        sudo ./${THIS_MASTER_BUILD_SCRIPT} [options]

        "
        exit 1;
    fi

    echo "Done checkUser()"

}

function checkInput()
{
    echo "Begin checkInput(): parameters=$@"

    for i in "$@"
    do
        case $i in
            -p=*|--platform=*)
            PLATFORM="${i#*=}"
            shift
            ;;
            -a=*|--architecture=*)
            ARCHITECTURE="${i#*=}"
            shift
            ;;
            -s=*|--subproject=*)
            SUBPROJECT="${i#*=}"
            shift
            ;;
            -v=*|--version=*)
            VERSION="${i#*=}"
            shift
            ;;
            -r|--rpm)
            RPM="rpm"
            shift
            ;;
            -i|--install)
            INSTALL="install"
            shift
            ;;
            -o=*|--install-options=*)
            INSTALL_OPTIONS="${o#*=}"
            shift
            ;;
            -h|--help)
                echo "

            Usage:
                -p|--platform: platform of sipxcom RPM to build, e.g. ${DEFAULT_PLATFORM} (default), rocky-9
                -a|--architecture: architecture of sipxcom RPM to build, e.g. ${DEFAULT_ARCHITECTURE} (default)
                -s|--subproject: subproject to build or sipx for building all RPMs, e.g. ${DEFAULT_SUBPROJECT} (default) sipXconfig
                -v|--version: version to build, e.g ${DEFAULT_VERSION} (default), 24.07
                -r|--rpm: include if building rpms
                -i|--install: include if installing rpms locally
                -o|--install-options: options for the install command to yum/dnf

            Sample:
                sudo sipxecs-build --platform=centos-7 --subproject=sipXconfig --version=25.01 --rpm --install
                sudo sipxecs-build -p=rocky-9 -a=x86_64 -s=sipXconfig -v=24.07
                "
                exit
            shift
            ;;
            *)
        esac
    done

    if [ -z "${PLATFORM}" ]
    then

        if [ -f /etc/centos-release ]; then

            CENTOS_VERSION=$(cat /etc/centos-release)
            CENTOS_VERSION=$(echo $CENTOS_VERSION | sed -e 's/^CentOS.*release //')
            CENTOS_VERSION=$(echo $CENTOS_VERSION | cut -d "." -f1)

            case $CENTOS_VERSION in

                "7")
                    PLATFORM=centos-7
                    ;;
                "9")
                    PLATFORM=centos-9
                    ;;
                *)
                    PLATFORM=${DEFAULT_PLATFORM}
                    ;;
            esac

        elif [ -f /etc/rocky-release ]; then

            ROCKY_VERSION=$(cat /etc/rocky-release)
            ROCKY_VERSION=$(echo $ROCKY_VERSION | sed -e 's/^Rocky.*release //')
            ROCKY_VERSION=$(echo $ROCKY_VERSION | cut -d "." -f1)

            case $ROCKY_VERSION in

                "9")
                    PLATFORM=rocky-9
                    ;;
                *)
                    PLATFORM=${DEFAULT_PLATFORM}
                    ;;
            esac
        fi
    else
        case $PLATFORM in

            "centos-7" | "centos-9" | "rocky-9")
                ;;

            *)
                echo "Error: Unknown platform ${PLATFORM}"
                exit 1
                ;;
        esac
    fi

    if [ -z "${ARCHITECTURE}" ]
    then
        ARCHITECTURE=${DEFAULT_ARCHITECTURE}
    else
        case $ARCHITECTURE in

        "x86_64")
            ;;

        *)
            echo "Error: Unknown architecture ${ARCHITECTURE}"
            exit 1
            ;;
        esac
    fi

    if [ -z "${SUBPROJECT}" ]
    then
        SUBPROJECT=${DEFAULT_SUBPROJECT}
    fi

    if [ -z "${VERSION}" ]
    then
        VERSION=${DEFAULT_VERSION}
    else
        case $VERSION in

        "24.01")
            ;;

        "25.01")
            ;;

        *)
            echo "Error: Unknown version ${VERSION}"
            exit 1
            ;;
        esac
    fi

    if [ -z "${INSTALL_OPTIONS}" ]
    then
        INSTALL_OPTIONS=${DEFAULT_INSTALL_OPTIONS}
    fi

    echo "Done checkInput(): PLATFORM=${PLATFORM}, ARCHITECTURE=${ARCHITECTURE}, SUBPROJECT=${SUBPROJECT}, VERSION=${VERSION}, INSTALL=${INSTALL}, INSTALL_OPTIONS=${INSTALL_OPTIONS}"
}

function checkSELinux()
{
    SELINUX_ENFORCED=$(grep 'SELINUX=enforcing' /etc/selinux/config)

    if [ ! -z ${SELINUX_ENFORCED} ]; then 

        echo "Detected SELinux enforcing, setting SELinux to disabled"

        sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config

        echo "A reboot is required to disable SELinux. Please login as root and run sipxecs-build after the reboot to continue building."
        
        read -p "Press Enter to reboot the system now: " 

        echo "Rebooting ..."
        
        sudo reboot
    fi
}

function init()
{
    echo "Begin init()"

    sudo mkdir -p ${BUILD_DIR}

    sudo chown -R ${SIPX_USER}.${SIPX_USER} ${SOURCE_DIR}

    echo "Done init()"
}

function addRepos() 
{
    echo "Begin addRepos()"

    wget -O /etc/yum.repos.d/sipxcom.repo \
        https://storage.googleapis.com/sipxecs/sipxcom/${VERSION}/${PLATFORM}-${ARCHITECTURE}/sipxcom.repo

    case $PLATFORM in

        "centos-7")
            addCentOS7Repos
            ;;

        "centos-9")
            addCentOS9Repos
            ;;

        "rocky-9")
            addRocky9Repos
            ;;

        *)
            echo "Error: Unknown platform ${PLATFORM}"
            exit 1
            ;;
    esac

    echo "Done addRepos()"
}

function addCentOS7Repos() 
{
    echo "Begin addCentOS7Repos()"

    LOCAL_REPO=${BUILD_DIR}/repo/CentOS_7/${ARCHITECTURE}

    echo "Done addCentOS7Repos()"
}

function addCentOS9Repos() 
{
    echo "Begin addCentOS9Repos()"

    LOCAL_REPO=${BUILD_DIR}/repo/CentOS_9/${ARCHITECTURE}

    rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    wget -O /etc/yum.repos.d/elasticsearch.repo \
      https://storage.googleapis.com/sipxecs/artifact-registry/elasticsearch.repo

    wget -O /etc/yum.repos.d/mongodb-org-8.0.repo \
      https://storage.googleapis.com/sipxecs/artifact-registry/mongodb-org-8.0.repo

    echo "Done addCentOS9Repos()"
}

function addRocky9Repos() 
{
    echo "Begin addRocky9Repos()"

    LOCAL_REPO=${BUILD_DIR}/repo/Rocky_9/${ARCHITECTURE}

    rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

    wget -O /etc/yum.repos.d/elasticsearch.repo \
      https://storage.googleapis.com/sipxecs/artifact-registry/elasticsearch.repo

    wget -O /etc/yum.repos.d/mongodb-org-8.0.repo \
      https://storage.googleapis.com/sipxecs/artifact-registry/mongodb-org-8.0.repo

    echo "Done addRocky9Repos()"
}


function setupCentOS7() 
{
    echo "Begin setupCentOS7()"

    yum remove -y epel-release

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "error removing epel-release, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    sudo yum install ${INSTALL_OPTIONS} make autoconf automake 

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "yum install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    sed -i 's/obsoletes=1/obsoletes=0/' /etc/yum.conf

    sudo yum install ${INSTALL_OPTIONS} libtool gcc-c++ openssl-devel libmcrypt-devel libtool-ltdl-devel \
        pcre-devel pcre-devel findutils  db4-devel iptables iproute boost-devel libpcap-devel libdnet-devel xmlrpc-c-devel \
        libevent-devel poco-devel libconfig-devel hiredis-devel gtest-devel leveldb-devel cppunit-devel gperftools-devel \
        c-ares-devel libdb4-cxx-devel libdb-cxx-devel popt-devel xerces-c-devel zeromq-devel libev-devel v8-devel httpd unixODBC-devel \
        mock rsync gem systemd-sysv mongo-cxx-driver-devel libuuid-devel swig openfire resiprocate-libs \
        dart-sdk createrepo unzip checkpolicy policycoreutils policycoreutils-python freeswitch-devel bcg729-devel java-17-openjdk-devel 

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "yum install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    cd ${SOURCE_DIR}    
    sudo mkdir -p /usr/local/sipx
    sudo chown sipx.sipx /usr/local/sipx

    echo "Using legacy oss_core for CentOS"
    sudo yum install -y oss_core oss_core-devel oss_core-debuginfo
    sudo mkdir -p /usr/local/sipx/lib
    sudo ln -s /usr/lib64/liboss_core.la /usr/local/sipx/lib/liboss_core.la
    sudo ln -s /usr/lib64/liboss_carp.la /usr/local/sipx/lib/liboss_carp.la
    sudo mkdir -p /usr/local/sipx/opt
    sudo ln -s /usr/opt/ossapp /usr/local/sipx/opt/ossapp

    cd ${BUILD_DIR}
    sudo echo oss_core > .modules-exclude

    if [ "${RPM}" != "" ]; then
        sudo yum install ${INSTALL_OPTIONS} createrepo rpm-build mock
        sudo wget http://li.nux.ro/download/nux/misc/el7/x86_64/thttpd-2.25b-33.el7.nux.x86_64.rpm
        sudo rpm -ivh thttpd-2.25b-33.el7.nux.x86_64.rpm
        rm -f thttpd-2.25b-33.el7.nux.x86_64.rpm
        sudo usermod -a -G mock sipx        
    fi

    echo "Done setupCentOS7()"
}

function setupCentOS9() 
{
    echo "Begin setupCentOS9()"


    echo "Done setupCentOS9()"
}

function setupRocky9() 
{
    echo "Begin setupRocky9()"

    echo "installing build tools"
    sudo dnf install ${INSTALL_OPTIONS} make autoconf automake libtool epel-release cmake gem httpd hostname

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "installing standard base OS repo tools"
    sudo dnf install ${INSTALL_OPTIONS} libtool gcc-c++ openssl-devel boost-devel poco-devel java-17-openjdk-devel 

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "installing standard devel repo tools"
    dnf config-manager --enable devel
    #sudo dnf install ${INSTALL_OPTIONS}  v8-devel policycoreutils-python-utils gcc-plugin-devel

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "installing epel repo tools"
    dnf config-manager --enable epel
    #sudo dnf install ${INSTALL_OPTIONS} gperftools-devel poco-devel gtest-devel hiredis-devel leveldb-devel libdnet-devel libmcrypt-devel mongo-c-driver-devel utf8proc-devel

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "installing crb repo tools"
    dnf config-manager --enable crb
    # sudo dnf install ${INSTALL_OPTIONS} cppunit-devel poco-devel zeromq-devel cppzmq-devel libconfig-devel libpcap-devel libsrtp-devel libdb-cxx-devel

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "installing rpms from sipXecs repo"
    dnf config-manager --enable sipxcom
    sudo dnf install ${INSTALL_OPTIONS} freeswitch-devel

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    if [ "${SUBPROJECT}" != "mongo-cxx-driver" ] && [ "${SUBPROJECT}" != "lib" ]; then
        echo "installing mongo-cxx-driver from sipxcom repo"
        sudo dnf install ${INSTALL_OPTIONS} mongo-cxx-driver-devel 

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 
    fi

    if [ "${SUBPROJECT}" != "jetty" ] && [ "${SUBPROJECT}" != "lib" ]; then
        echo "installing jetty from sipxcom repo"
        sudo dnf install ${INSTALL_OPTIONS} jetty 

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 
    fi

    if [ "${SUBPROJECT}" != "cfengine" ] && [ "${SUBPROJECT}" != "lib" ]; then
        echo "installing cfengine from sipxcom repo"
        sudo dnf install ${INSTALL_OPTIONS} cfengine-community

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 
    fi

    if [ "${SUBPROJECT}" != "dart-sdk" ] && [ "${SUBPROJECT}" != "lib" ]; then
        echo "installing dart-sdk from sipxcom repo"
        sudo dnf install ${INSTALL_OPTIONS} dart-sdk

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 
    fi

    echo "installing elasticsearch from elasticsearch repo"
    dnf config-manager --enable elasticsearch
    sudo dnf install ${INSTALL_OPTIONS} elasticsearch

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "installing MongoDB from mongodb-org-8.0 repo"
    dnf config-manager --enable mongodb-org-8.0
    sudo dnf install ${INSTALL_OPTIONS} mongodb-org

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "dnf install error, exiting sipxecs-build"
        exit ${ERROR}
    fi 
    

    if [ "${RPM}" != "" ]; then

        echo "Setting rpmbuild to ${BUILD_DIR}/rpmbuild"
	    echo "%_topdir      ${BUILD_DIR}/rpmbuild" >> ~/.rpmmacros

        echo "installing standard RPM tools"
        sudo dnf install ${INSTALL_OPTIONS} createrepo rpm-build podman

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 

        echo "installing crb RPM tools"
        dnf config-manager --enable crb
        sudo dnf install ${INSTALL_OPTIONS} mock

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 
        sudo usermod -a -G mock sipx

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 

        echo "installing  other sipxcom RPM tools"
        sudo dnf install ${INSTALL_OPTIONS} thttpd 

        ERROR=$?
        if [ ${ERROR} -ne 0 ]; then 
            echo "dnf install error, exiting sipxecs-build"
            exit ${ERROR}
        fi 
    fi

    # cd ${BUILD_DIR}
    # sudo echo oss_core > .modules-exclude

    echo "Done setupRocky9()"
}


function configureCentOS7() 
{
    echo "Begin configureCentOS7()"

    sed -i "/^AC_INIT.*/ s//AC_INIT(sipX, ${VERSION}, ${SIPXCOM_USER_GROUP})/" ${SOURCE_DIR}/configure.ac

    cd ${SOURCE_DIR}
    sudo autoreconf -ivf

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "autoreconf error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    cd ${BUILD_DIR}

    sudo echo '$(sipx_all)' > .modules-include

    if [ -z "${RPM}" ]; then
        sudo ../configure
    else
        sudo ../configure --enable-rpm DISTRO="${PLATFORM}-${ARCHITECTURE}"
    fi

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "configure error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "Done configureCentOS7()"
}

function configureCentOS9() 
{
    echo "Begin configureCentOS9()"

    echo "Done configureCentOS9()"
}

function configureRocky9() 
{
    echo "Begin configureRocky9()"

    sed -i "/^AC_INIT.*/ s//AC_INIT(sipX, ${VERSION}, ${SIPXCOM_USER_GROUP})/" ${SOURCE_DIR}/configure.ac

    cd ${SOURCE_DIR}
    sudo autoreconf -ivf

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "autoreconf error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    cd ${BUILD_DIR}

    sudo echo '$(sipx_all)' > .modules-include

    if [ -z "${RPM}" ]; then
        sudo ../configure
    else
        sudo ../configure --enable-rpm DISTRO="${PLATFORM}-${ARCHITECTURE}"
    fi

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "configure error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "Done configureRocky9()"
}


function build() 
{
    echo "Begin build()"

    cd ${BUILD_DIR}

 
    # The make command may kick a permission error when creating RPMs

    if [ -z "${RPM}" ]; then

        sudo make ${SUBPROJECT}
    
    else

        echo "RPMs will be generated locally at ${LOCAL_REPO}"

        sudo make ${SUBPROJECT}.rpm       
    fi

    ERROR=$?
    if [ ${ERROR} -ne 0 ]; then 
        echo "make error, exiting sipxecs-build"
        exit ${ERROR}
    fi 

    echo "Done build()"
}

function install() 
{
    echo "Begin install()"

    cd ${BUILD_DIR}

    # 'repomanage' lists the most recent RPMs in a directory
    sudo yum localinstall ${INSTALL_OPTIONS} $(repomanage ${LOCAL_REPO})

    echo "Done install()"
}

function main()
{

    echo "Starting ${THIS_MASTER_BUILD_SCRIPT}"

    checkUser

    checkInput $@

    checkSELinux

    init

    addRepos

    case $PLATFORM in

        "centos-7")
            setupCentOS7
            configureCentOS7
            ;;

        "centos-9")
            setupCentOS9
            configureCentOS9
            ;;

        "rocky-9")
            setupRocky9
            configureRocky9
            ;;

        *)
            echo "Error: Unknown platform ${PLATFORM}"
            exit 1
            ;;
    esac
    
    build

    if [ ! -z "${INSTALL}" ]; then

        install

    fi

    echo "Finished ${THIS_MASTER_BUILD_SCRIPT}"
}

main $@