#!/bin/bash

SIPX_USER=sipx

DEFAULT_PLATFORM=centos-7

DEFAULT_ARCHITECTURE=x86_64

DEFAULT_SUBPROJECT=sipx

DEFAULT_VERSION=24.01

SIPXCOM_USER_GROUP=sipxcom-dev@googlegroups.com

THIS_MASTER_BUILD_SCRIPT=$(readlink -f ${BASH_SOURCE[0]})

SOURCE_DIR=$(dirname ${THIS_MASTER_BUILD_SCRIPT})

BUILD_DIR=${SOURCE_DIR}/build

LOCAL_REPO=

function checkUser()
{
    echo "Begin checkUser(): SUDO_USER=${SUDO_USER}, USER=${USER}, SIPX_USER=${SIPX_USER}"

    if [ "${SUDO_USER}" != "${SIPX_USER}" ] || [ "${USER}" != "root" ]; then
        echo "
        Error: You must run this script with sudo root privileges as user ${SIPX_USER}. 
        
        Please setup your instance as follows:

        yum update -y
        
        useradd -m ${SIPX_USER}

        passwd ${SIPX_USER}

        visudo (append):
            # add ${SIPX_USER} as sudo user
            ${SIPX_USER}    ALL=(ALL)       NOPASSWD:ALL

        yum install -y sudo

        su ${SIPX_USER}

        sudo ./${THIS_MASTER_BUILD_SCRIPT} [options]

        "
        exit 1;
    fi

    echo "Done checkUser()"

}

function checkInput()
{
    echo "Begin checkInput(): options=$@"

    for i in "$@"
    do
        case $i in
            -p=*|--platform=*)
            PLATFORM="${i#*=}"
            shift
            ;;
            -a=*|--architecture=*)
            ARCHITECTURE="${i#*=}"
            shift
            ;;
            -s=*|--subproject=*)
            SUBPROJECT="${i#*=}"
            shift
            ;;
            -v=*|--version=*)
            VERSION="${i#*=}"
            shift
            ;;
            -r|--rpm)
            RPM="rpm"
            shift
            ;;
            -i|--install)
            INSTALL="install"
            shift
            ;;
            -h|--help)
                echo "

            Usage:
                -p|--platform: platform of sipxcom RPM to build, e.g. ${DEFAULT_PLATFORM} (default), rocky-9
                -a|--architecture: architecture of sipxcom RPM to build, e.g. ${DEFAULT_ARCHITECTURE} (default)
                -s|--subproject: subproject to build or sipx for building all RPMs, e.g. ${DEFAULT_SUBPROJECT} (default) sipXconfig
                -v|--version: version to build, e.g ${DEFAULT_VERSION} (default), 24.07
                -r|--rpm: include if building rpms
                -i|--install: include if installing rpms locally

            Sample:
                sudo sipxecs-build --platform=centos-7 --subproject=sipXconfig --version=24.01 --rpm --install
                sudo sipxecs-build -p=rocky-9 -a=x86_64 -s=sipXconfig -v=24.07
                "
                exit
            shift
            ;;
            *)
        esac
    done

    if [ -z "${PLATFORM}" ]
    then

        CENTOS_VERSION=$(cat /etc/centos-release)
        CENTOS_VERSION=$(echo $CENTOS_VERSION | sed -e 's/^CentOS.*release //')
        CENTOS_VERSION=$(echo $CENTOS_VERSION | cut -d "." -f1)

        case $CENTOS_VERSION in

            "7")
                PLATFORM=centos-7
                ;;
            "9")
                PLATFORM=centos-9
                ;;
            *)
                PLATFORM=${DEFAULT_PLATFORM}
                ;;
        esac

    else
        case $PLATFORM in

            "centos-7" | "centos-9" | "rocky-9")
                ;;

            *)
                echo "Error: Unknown platform ${PLATFORM}"
                exit 1
                ;;
        esac
    fi

    if [ -z "${ARCHITECTURE}" ]
    then
        ARCHITECTURE=${DEFAULT_ARCHITECTURE}
    else
        case $ARCHITECTURE in

        "x86_64")
            ;;

        *)
            echo "Error: Unknown architecture ${ARCHITECTURE}"
            exit 1
            ;;
        esac
    fi

    if [ -z "${SUBPROJECT}" ]
    then
        SUBPROJECT=${DEFAULT_SUBPROJECT}
    fi

    if [ -z "${VERSION}" ]
    then
        VERSION=${DEFAULT_VERSION}
    else
        case $VERSION in

        "24.01")
            ;;

        *)
            echo "Error: Unknown version ${VERSION}"
            exit 1
            ;;
        esac
    fi

    echo "Done checkInput(): PLATFORM=${PLATFORM}, ARCHITECTURE=${ARCHITECTURE}, SUBPROJECT=${SUBPROJECT}, VERSION=${VERSION}, INSTALL=${INSTALL}"
}

function checkSELinux()
{
    SELINUX_ENFORCED=$(grep 'SELINUX=enforcing' /etc/selinux/config)

    if [ ! -z ${SELINUX_ENFORCED} ]; then 

        echo "Detected SELinux enforcing, setting SELinux to disabled"

        sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config

        echo "A reboot is required to disable SELinux. Please login as root and run sipxecs-build after the reboot to continue building."
        
        read -p "Press Enter to reboot the system now: " 

        echo "Rebooting ..."
        
        sudo reboot
    fi
}

function init()
{
    echo "Begin init()"

    sudo mkdir -p ${BUILD_DIR}

    sudo chown -R ${SIPX_USER}.${SIPX_USER} ${SOURCE_DIR}

    echo "Done init()"
}

function setupRepos() 
{
    echo "Begin setupRepos()"

    yum remove -y epel-release

    wget -O /etc/yum.repos.d/sipxcom.repo \
        https://storage.googleapis.com/sipxecs/sipxcom/${VERSION}/${PLATFORM}-${ARCHITECTURE}/sipxcom.repo

    case $PLATFORM in

        "centos-7")
            LOCAL_REPO=${BUILD_DIR}/repo/CentOS_7/${ARCHITECTURE}
            ;;

        "centos-9")
            LOCAL_REPO=${BUILD_DIR}/repo/CentOS_9/${ARCHITECTURE}
            ;;

        "rocky-9")
            LOCAL_REPO=${BUILD_DIR}/repo/Rocky_9/${ARCHITECTURE}
            ;;

        *)
            echo "Error: Unknown platform ${PLATFORM}"
            exit 1
            ;;
    esac

    echo "Done setupRepos()"
}

main $@