#!/bin/bash

THIS_MASTER_REMOVE_SCRIPT=$(readlink -f ${BASH_SOURCE[0]})

SOURCE_DIR=$(dirname ${THIS_MASTER_REMOVE_SCRIPT})

function checkUser()
{
    echo "Begin checkUser(): USER=${USER}"

    if [ "${USER}" != "root" ]; then
        echo "
        Error: You must run this script as root. 
        "
        exit 1;
    fi

    echo "Done checkUser()"

}

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
REVERT_TO_TAG=$@

git checkout ${REVERT_TO_TAG}
ERROR=$?
if [ ${ERROR} -ne 0 ]; then 
    echo "git checkout error, exiting sipxecs-revert"
    exit ${ERROR}
fi
mkdir -p ../${REVERT_TO_TAG}
cp -r . ../${REVERT_TO_TAG}
git checkout ${CURRENT_BRANCH}
ERROR=$?
if [ ${ERROR} -ne 0 ]; then 
    echo "git checkout error, exiting sipxecs-revert"
    exit ${ERROR}
fi
\cp -rf ../${REVERT_TO_TAG}/* .