  <!DOCTYPE script PUBLIC
  "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
  "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
  <script>
  <include-script resource-path="/org/sipfoundry/sipxconfig/js/jquery-3.7.1.min.js"/>
  <include-script resource-path="/org/sipfoundry/sipxconfig/js/jquery-migrate-3.4.1.min.js"/>  
  <body>
    <![CDATA[
this.loadRSS = function(){
	    $.get('https://viewme.ezuce.com/sipxcom-feed', function (data) {
var content = "";
    $(data).find("item").each(function () { // or "item" or whatever suits your feed
        var el = $(this);
		content = content + "<a href='"+el.find("link").text() + "' target='_blank'>" + el.find("title").text() + "</a><br/>";
    });
	var theDiv = document.getElementById("rssDiv");
	theDiv.innerHTML = content;
});
}
    ]]>
  </body>
  <initialization>
    jQuery(document).ready(function() {
    	loadRSS();
	});
  </initialization>
</script>
