include $(top_srcdir)/config/utility.am

confdir = $(SIPX_DATADIR)/schema
# dtd useful for projects that want to validate spring files w/o hitting the internet
dist_conf_DATA = \
	spring-beans.xsd \
	spring-util.xsd \
	spring-task.xsd \
	spring-security.xsd \
	spring-all.xsd \
	jaxrs.xsd \
	spring-context.xsd \
	spring-mvc.xsd \
	spring-websocket.xsd \
	core.xsd
