#Created by JInto - www.guh-software.de
#Thu Oct 05 17:46:56 CEST 2006
menu.about=About
menu.voicemail=Voicemail
menu.inbox=Inbox
menu.distributionLists=Distribution
menu.callForwarding=Forwarding
menu.changePin=Change PIN
menu.speedDial=Speed Dial
menu.managePresence=Agent
menu.myInformation=Me
menu.registrations=Phones
menu.schedules=Schedules
menu.phonebook=Phonebook
menu.userCdr=Call History
