<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
    "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
    "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>
  <include-script resource-path="/org/sipfoundry/sipxconfig/site/search/search-panel.js" />
  <input-symbol key="placeholder" required="yes" />
  <input-symbol key="queryField" required="yes" />
  <initialization>
    var searchBox = dojo.byId('${queryField.clientId}');
    searchPanel.register(searchBox, '${placeholder}');
  </initialization>
</script>
