# Core server support
--module=server

# HTTP and HTTPS connectors
--module=http
# Must be started on commandline since server creates certs
#--module=https

# Web application support with Jakarta EE 10
--module=ee10-annotations
--module=ee10-deploy
--module=ee10-webapp
--module=ee10-servlet
--module=ee10-jsp

# sipXconfig jars symlinked in
--module=ext
