<!DOCTYPE script PUBLIC
  "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
  "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>
  <body>
    <![CDATA[
      function checkAll(event) {
        var master = event.target;
        var form = document.forms["refreshForm"];
        if (!form) return;

        var changeTo = master.checked;

        var elements = form.elements;
        for (var i = 0; i < elements.length; i++) {
          var el = elements[i];

          if (
            el.type === "checkbox" &&
            el.id !== "controlCheckbox"
          ) {
            el.checked = changeTo;
          }
        }
      }
    ]]>
  </body>

  <initialization>
    var checkBoxAll = document.getElementById("controlCheckbox");
    if (checkBoxAll) {
      checkBoxAll.addEventListener("click", checkAll);
    }
  </initialization>
</script>